In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("iowa.csv")

In [6]:
# analyte column

,Unnamed: 0,ANALYTE,RESULTS,Collection Date,FACILITY NAME,Facility ID
0,1,11CL-PF3OUDS,< 1.9 ng/L,01/31/2022,S/EP FRM WELLS #1 & #2 AFTER TRT (FINISHED DRI...,02
1,2,9CL-PF3ONS,< 1.9 ng/L,01/31/2022,S/EP FRM WELLS #1 & #2 AFTER TRT (FINISHED DRI...,02
2,3,ADONA,< 1.9 ng/L,01/31/2022,S/EP FRM WELLS #1 & #2 AFTER TRT (FINISHED DRI...,02
3,4,HFPO-DA,< 1.9 ng/L,01/31/2022,S/EP FRM WELLS #1 & #2 AFTER TRT (FINISHED DRI...,02
4,5,NONAFLUORO NFDHA,< 1.9 ng/L,01/31/2022,S/EP FRM WELLS #1 & #2 AFTER TRT (FINISHED DRI...,02
...,...,...,...,...,...,...
72,73,PERFLUOROOCTANE SULFONIC ACID 6:2 FTS,< 1.9 ng/L,01/31/2022,WELL # 2 (1996) (RAW WATER),WL02
73,74,PERFLUOROPENTANESULFONIC ACID (PFPES),< 1.9 ng/L,01/31/2022,WELL # 2 (1996) (RAW WATER),WL02
74,75,PERFLUOROPENTANOIC ACID (PFPEA),< 1.9 ng/L,01/31/2022,WELL # 2 (1996) (RAW WATER),WL02
75,76,PERFLUOROUNDECANOIC ACID (PFUNA),< 1.9 ng/L,01/31/2022,WELL # 2 (1996) (RAW WATER),WL02
76,77,TOTAL PFOA AND PFOS,< 2.0 ng/L,01/31/2022,WELL # 2 (1996) (RAW WATER),WL02

In [8]:
df["RESULTS"].str.split(" ")

0     [<, 1.9, ng/L]
1     [<, 1.9, ng/L]
2     [<, 1.9, ng/L]
3     [<, 1.9, ng/L]
4     [<, 1.9, ng/L]
           ...
72    [<, 1.9, ng/L]
73    [<, 1.9, ng/L]
74    [<, 1.9, ng/L]
75    [<, 1.9, ng/L]
76    [<, 2.0, ng/L]
Name: RESULTS, Length: 77, dtype: object